name = "mirror-gallery"
compatibility_date = "2026-04-05"
pages_build_output_dir = "."

[[d1_databases]]
binding = "PHOTO_DB"
database_name = "mirror-photo-metadata"
database_id = "84d8ecbc-7578-474f-aec3-1401fbbf3822"

[[r2_buckets]]
binding = "PHOTO_BUCKET"
bucket_name = "mirror-gallery"
