name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Process config template
        run: |
          # Replace environment variables in config template
          envsubst < config.template.js > config.js
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          UPLOAD_PASSWORD_HASH: ${{ secrets.UPLOAD_PASSWORD_HASH }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: .
          # Optional: Use wrangler-version to be explicit about the version to use.
          # wrangler-version: '3'
